version: '3'
services:
  docs:
    build:
      context: docs
    develop:
      watch:
        - path: ./docs
          target: /opt/app/
          action: sync
          ignore:
            - 'node_modules'
            - '.vitepress/dist'
            - '.vitepress/cache'
    ports:
      - '5173:5173'
  linux:
    build:
      dockerfile: '.build/os/linux/Dockerfile'
    volumes:
      - ./dist/linux:/opt/app/dist/linux
  windows:
    build:
      dockerfile: '.build/os/windows/Dockerfile'
    volumes:
      - ./dist/windows:/opt/app/dist/windows