version: '3'
services:
  docs:
    build:
      context: .docs
    develop:
      watch:
        - path: ./.docs
          target: /opt/app/
          action: sync
          ignore:
            - 'node_modules'
            - '.vitepress/dist'
            - '.vitepress/cache'
    ports:
      - '5173:5173'
  linux-build:
    image: rust:latest
    command: tail -f dev/null
    volumes:
      - .:/opt/app