name: Deploy release

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-release:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build release with docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.build.yml"
      - name: Create archive for executable
        shell: bash
        run: |
          7z a taskify-windows.zip .build/dist/windows
          tar -czf taskify-linux.tar.gz .build/dist/linux
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "0.1.0"
          files: |
            taskify-windows.zip
            taskify-linux.tar.gz
