name: Deploy release

on:
  push:
permissions:
  contents: write

jobs:
  deploy-release:
    if: startsWith(github.ref_name, 'release-')
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build release with docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: |
            linux
            windows
      - name: Create archive for executable
        shell: bash
        run: |
          7z a taskify-windows.zip dist/windows
          tar -czf taskify-linux.tar.gz dist/linux
          echo "Version: ${{github.ref_name}}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          files: |
            taskify-windows.zip
            taskify-linux.tar.gz
